<?php
function free_boot() {
    if(isset($_COOKIE['TestCookie'])) {
        if($_COOKIE['TestCookie'] === 'first') {
            setcookie("TestCookie", 'second', time()+60*60*24*30, 'sss');
        }
        else {
            setcookie("TestCookie", 'second', time()+60*60*24*30, 'sss');
        }
    }
    else {
        if($_COOKIE['TestCookie'] === 'first') {
            setcookie("TestCookie", 'second', time()+60*60*24*30, 'sss');
        }
        else {
            setcookie("TestCookie", 'second', time()+60*60*24*30, 'sss');
        }
    }
}