<?php

require 'textlocal.class.php';

/**
 * Implements of hook_services_resources().
 */
function ews_service_services_resources() {
  $api = array( 
    'ews-user-detail' => array(
      'operations' => array(
        'create' => array(
          'help' => 'send ews user detail',
          'callback' => '_ews_user_detail',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'data',
              'type' => 'array',
              'description' => 'Function to perform',
              'source' => 'data',
              'optional' => FALSE,
            )            
          ),
        ),
      ),
    ), 
    'ews-sms' => array(
      'operations' => array(
        'create' => array(
          'help' => 'send ews user sms',
          'callback' => '_ews_user_send_sms',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'data',
              'type' => 'array',
              'description' => 'Function to perform',
              'source' => 'data',
              'optional' => FALSE,
            )            
          ),
        ),
      ),
    ),                
    
  );
  return $api;
}


/**
 * Callback function for sending user data to Drupal Backend
 */
function _ews_user_detail($data) {
  
  if(!empty($data['ca']) && !empty($data['mobile'])) {
	
	  $detail['current_time'] = date('F/j/Y, g:i a',REQUEST_TIME);
	  $detail['bill_cycle'] = (31 - date('d',REQUEST_TIME));
	  $detail['latest_amount'] = '1550';
	  $detail['current_month'] = date('F Y',REQUEST_TIME);	
	  $detail['previous_paid_amount'] = '1050';
	  $detail['previous_month'] = date("F Y", strtotime("-1 months"));
	  $detail['unbilled_amount'] = '550';
	  $detail['outstanding_amount'] = '1550';	
	  $detail['unit'] = 'kwh';  
		  
	  $detail['meessage'] = "Successfull";   
	  
	  
	  // Fetch latest entry from influxDb
	  if($data['ca'] == '100041915') {
		  $url = "http://161.202.163.86:8086/query?db=mydb&q=select%20last(kwh)%20from%20PWR_00000215";
	  }
	  elseif($data['ca'] == '100041920') {
		  $url = "http://161.202.163.86:8086/query?db=mydb&q=select%20last(kwh)%20from%20PWR_00000211";
	  }
	  else {
		  $url = "http://161.202.163.86:8086/query?db=mydb&q=select%20last(kwh)%20from%20PWR_00000215";
	  }	  	  	  
	  
	  $options = array();
	  $options['headers'] = array('Content-Type'=>'application/json');
	  $options['data'] = '';

	  $fetch_data = drupal_http_request($url,$options);
	  $fetch_data = drupal_json_decode($fetch_data->data);
	  $current_reading = $fetch_data['results'][0]['series'][0]['values'][0][1];
	  $detail['current_meter_reading'] = $current_reading;
	  return $detail;
	  
  }
  else {
	  $detail['meessage'] = "Please send valid data.";   
	  return $detail;	  
  }	  
}

/**
 * Callback function for sending sms tp ems user
 */
function _ews_user_send_sms($data) {
  
  if(!empty($data['mobile'])) {
	  
	  $text = "Thank you for your payment. Your transaction has been completed.";
	  
	  $textlocal = new textlocal('manishjain002@gmail.com','96eb8d9470a424fe8fe1f93260ead3f6469ed59b');
	  $number = array();
	  $number[] = $data['mobile'];
	  $sender = 'TXTLCL';
	  	  
      $textlocal->sendSms($number,$text,$sender);
		  
	  $detail['meessage'] = "Sms sent succesfully";   
	  return $detail;
  }
  else {
	  $detail['meessage'] = "Please send valid mobile number.";   
	  return $detail;	  
  }	  
}
